apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sidecar-terminator
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sidecar-terminator
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get","list","create","update","watch","patch","delete"]
  resourceNames: ["sidecar-terminator"]
